config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users, :path_prefix => 'account'
  resources :users
  resources :videos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :show, to: :read
    alias_action :index, :show, :new, :edit, :update, :destroy, to: :crud

    user ||= User.new
    if user.admin?
      can :manage, :all
      can :manage, User
    else
      can :default, Video
      can :crud, Video do |item|
        item.user.id == user.id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include ActionView::Helpers
  before_create :set_role
  has_many :videos, dependent: :destroy
  has_enumeration_for :role, with: UserRole, create_helpers: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_role
    self.role ||= UserRole::DEFAULT
  end
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  belongs_to :user

  validates :titulo, presence: true
  validates :url, presence: true,
                  format: { with: /([^\s]+(\.(m3u8)))/i,
                            message: 'Por favor, digite uma url no formato .m3u8' }

  def update_views
    self.views += 1
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @videos = Video.paginate(page: params[:page], per_page: 6)
                   .order('created_at DESC')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  # GET /users
  def index
    @users = User.includes(:videos)
                 .paginate(page: params[:page], per_page: 20)
                 .order('created_at DESC')
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: notice_msg('criado') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: notice_msg('atualizado') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: notice_msg('destruido') }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def notice_msg(action)
    "User #{action} com Sucesso!"
  end

  def user_params
    params.require(:user).permit(:email, :password, :role)
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  before_action :set_video, only: %i[show edit update destroy]

  # GET /videos
  def index
    @videos = Video.where(user_id: current_user.id)
                   .paginate(page: params[:page], per_page: 20)
                   .order('created_at DESC')
  end

  # GET /videos/1
  def show; end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit; end

  # POST /videos
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: notice_msg('criado') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /videos/1
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: notice_msg('atualizado') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /videos/1
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: notice_msg('destruido') }
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def notice_msg(action)
    "Video #{action} com Sucesso!"
  end

  def video_params
    params.require(:video).permit(:titulo, :url, :views)
          .merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: 'card border-danger') do
        concat(content_tag(:div, class: 'card-header bg-danger text-white') do
          concat "#{pluralize(object.errors.count, 'error')} proibiu que este #{object.class.name.downcase} fosse salvo: "
        end)
        concat(content_tag(:ul, class: 'mb-0 list-group list-group-flush') do
          object.errors.full_messages.each do |msg|
            concat content_tag(:li, msg, class: 'list-group-item')
          end
        end)
      end
    end
  end
end

app/views/home/index.html.erb
<h2 class="title">Todos Vídeos</h2>
<div class="row">
  <% if @videos.present? %>
    <% @videos.each do |video| %>
      <div class="col-md-4">
        <a href="<%= video_path(video) %>">
          <div class="card mb-4 box-shadow">
            <video id="my_video_<%= video.id %>" class="video-js vjs-default-skin card-img-top" controls preload="auto" data-setup='{}'>
              <source src=" <%= video.url %>" type="application/x-mpegURL">
            </video>
          </a>
          <div class="card-body">
            <p class="card-text title"><%= video.titulo %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <% if can? :crud, video %>
                  <%= link_to 'Editar', edit_video_path(video), class: "btn btn-sm btn-warning" %>
                  <%= link_to 'Apagar', video, method: :delete, data: { confirm: 'Deseja remover?' }, class: "btn btn-sm btn-danger" %>
                <% end %>
              </div>
              <small class="text-muted"><%= video.views %> Visitas</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <h2>Nehum Video Cadastrado</h2> 
  <% end %>
</div>
<div class="row col-md-3 offset-md-5">
  <%= will_paginate @videos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/layouts/_message.html.erb
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="alert alert-success">
      <% elsif type == "alert" %>
        <div class="alert alert-danger">
      <% else %>
        <div class='alert alert-<%= "#{type}" %>'>
      <% end %>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
     
      <%= msg %>
        
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetshowMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%= stylesheet_link_tag  'home' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark "> 
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
        data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" 
        aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
            <div class="collapse navbar-collapse" id="navbarsExample02">
                <ul class="navbar-nav mr-auto">
                    <li><a class="navbar-brand" href="<%= root_path %>">NetshowMe</a></li>
                </ul>
                <form class="form-inline my-2 my-md-0"> </form>
            </div>
        <a href="#menu-toggle" id="menu-toggle" class="navbar-brand"><span class="navbar-toggler-icon"></span></a>
        </nav>
        <div id="wrapper" class="toggled">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class=" sidebar-brand"> <a href=""> <%= current_user.email %> </a> </li>
                    <li><a href="<%= root_path %>">Início</a></li>
                    <li> <a href="<%= new_video_path  %>">Novo Video</a> </li>
                    <li> <a href="<%= videos_path  %>">Meus Videos</a> </li>
                    <% if can? :manager, User %>
                      <li><a class="sidebar-brand" href="#">Usuários</a></li>
                      <li> <a href="<%= new_user_path  %>">Novo Usuários</a> </li>
                      <li> <a href="<%= users_path  %>">Lista Usuários</a> </li>
                    <% end %>
                    <li> <%= link_to 'Sair', destroy_user_session_path,
                     method: :delete, class: "text_center_al" %> </li>
                </ul>
            </div> <!-- /#sidebar-wrapper -->
            <!-- Page Content -->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                  <div class="col-md-10 offset-md-1">
                    <%= render './layouts/message' %>
                  </div>
                  <div>
                    <%= yield %>
                  </div>
                </div>
            </div> <!-- /#page-content-wrapper -->
        </div> <!-- /#wrapper -->
        
        <script>
          $(function(){
            $("#menu-toggle").click(function(e) {
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
            });

            $(window).resize(function(e) {
              if($(window).width()<=768){
                $("#wrapper").removeClass("toggled");
              }else{
                $("#wrapper").addClass("toggled");
              }
            });
          });
        </script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetshowMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag  'devise' %>
    <%= stylesheet_link_tag  'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="wrapper fadeInDown">
      <div id="formContent">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, html: {role: "form", class: "col-md-6 offset-md-3"} do |form| %>
  <% if @user.errors.any? %>
      <%= errors_for @user %></li>  
  <% end %>

  <div class="form-group">
    <%= form.label :email, required: true %>
    <%= form.text_field :email, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.text_field :password, class: "form-control" %>
  </div>

  <div class="form-group pmd-textfield">
    <%= form.label :role %>
    <%= form.select :role, UserRole.to_a, {}, { class: 'form-control' } %>
  </div>

  <div class="form-buttons float-right">
    <%= link_to 'Voltar', users_path, class: "btn btn-danger" %>
    <%= form.submit "Salvar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2 class="title">Editar User</h2>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h2 class="title">Lista de Users</h2>

<div class="table-responsive">
  <table class="table table-bordered table-dark">
    <thead>
      <tr >
        <th class="text_left_al">Email</th>
        <th class="text_left_al">Tipo</th>
        <th class="text_left_al">Videos</th>
        <th colspan="2" class="text_center_al"> Ações </th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= t(user.role) %></td>
          <td><%= user.videos.count %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Deseja remover?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="row col-md-3 offset-md-5">
  <%= will_paginate @Users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<%= link_to 'Novo User', new_user_path, class: "btn btn-success float-right" %>

app/views/users/new.html.erb
<h2 class="title">Novo User</h2>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/videos/_form.html.erb
<%= form_for @video, html: {role: "form", class: "col-md-6 offset-md-3"} do |form| %>
  <% if @video.errors.any? %>
      <%= errors_for @video %></li>  
  <% end %>

  <div class="form-group">
    <%= form.label :titulo, required: true %>
    <%= form.text_field :titulo, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :url, required: true %>
    <%= form.text_field :url, class: "form-control", required: true %>
  </div>

  <div class="form-buttons float-right">
    <%= link_to 'Voltar', videos_path, class: "btn btn-danger" %>
    <%= form.submit "Salvar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1 class="title">Editar Video</h1>

<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<h1 class="title">Meus Videos</h1>
<div class="table-responsive">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th class="text_left_al">Titulo</th>
        <th class="text_left_al">Url</th>
        <th class="text_left_al">Vizualizações</th>
        <th colspan="3" class="text_center_al"> Ações </th>
      </tr>
    </thead>

    <tbody>
      <% @videos.each do |video| %>
        <tr>
          <td><%= video.titulo %></td>
          <td><%= video.url %></td>
          <td><%= video.views %></td>
          <td><%= link_to 'Ver', video %></td>
          <td><%= link_to 'Editar', edit_video_path(video) %></td>
          <td><%= link_to 'Apagar', video, method: :delete, data: { confirm: 'Deseja remover?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<div class="row col-md-3 offset-md-5">
  <%= will_paginate @videos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<%= link_to 'Novo Video', new_video_path, class: "btn btn-success float-right" %>

app/views/videos/new.html.erb
<h1 class="title">Novo Video</h1>

<%= render 'form', video: @video %>

app/views/videos/show.html.erb
<h2 class="title"><%= @video.titulo.capitalize %><h2>
<div class="row">
  <div class="col-md-12">
    <div class="card mb-12 box-shadow">
      <video id="my_video_1" width=960 height=440 class="video-js vjs-default-skin card-img-top"
             controls preload="auto" data-setup='{}'>
        <source src="<%= @video.url %>" type="application/x-mpegURL">
      </video>
      <div class="card-body">
        <p class="card-text"><%#= @video.titulo.capitalize %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
          </div>
          <small class="text-muted"><%= @video.views %> Visitas</small>
        </div>
      </div>
    </div>
    <div class="form-group float-right">
    <%= link_to 'Voltar', videos_path, class: "btn btn-danger" %>
    <% if can? :crud, @video %>
      <%= link_to 'Editar', edit_video_path(@video), class: "btn btn-warning" %>
    <% end %>
  </div>
  </div>
 </div>

<script>
  var player = videojs('my_video_1');
  player.play();
  var arr = "<%= @video.update_views %>"
</script>